AbilityNamesToTexturesMapping = {
    ["Consecration"] = "Spell_Holy_InnerFire",
    ["Crusader Strike"] = "Spell_Holy_CrusaderStrike",
    ["Greater Blessing of Sanctuary"] = "Spell_Holy_GreaterBlessingOfSanctuary",
    ["Holy Shield"] = "Spell_Holy_BlessingOfProtection",
    ["Holy Strike"] = "INV_Sword_01",
    ["Judgement"] = "Spell_Holy_RighteousFury",
    ["Seal of Righteousness"] = "Ability_ThunderBolt",
    ["Seal of Wisdom"] = "Spell_Holy_RighteousnessAura",
    ["Furious Howl"] = "Ability_Hunter_Pet_Wolf",
    ["Feign Death"] = "Ability_Rogue_FeignDeath",
    -- Spells --
    ["Earth Shock"] = "Spell_Nature_EarthShock",
    ["Flame Shock"] = "Spell_Fire_FlameShock",
    ["Frost Shock"] = "Spell_Frost_FrostShock",
    ["Stormstrike"] = "ability_shaman_stormstrike",
    ["Lightning Strike"] = "Spell_Nature_ThunderClap",
    ["Lightning Bold"] = "Spell_Nature_Lightning",
    ["Chain Lightning"] = "Spell_Nature_ChainLightning",
    ["Molten Blast"] = "Spell_Fire_MeteorStorm",
    -- Shields --
    ["Lightning Shield"] = "Spell_Nature_LightningShield",
    ["Water Shield"] = "Ability_Shaman_WaterShield",
    ["Earth Shield"] = "Spell_Nature_SkinofEarth",
    -- Weapons --
    ["Windfury Weapon"] = "Spell_Nature_Cyclone",
    ["Rockbiter Weapon"] = "Spell_Nature_RockBiter",
    ["Flametongue Weapon"] = "Spell_Fire_FlameTounge",
    ["Frostbrand Weapon"] = "Spell_Frost_FrostBrand",
    -- Totems --
    ["Totemic Recall"] = "Spell_Shaman_TotemRecall",
    ["Strength of Earth"] = "Spell_Nature_StrengthOfEarthTotem02",
    ["Windfury Totem"] = "Spell_Nature_Windfury",
    ["Flametongue Totem"] = "",
    ["Temor Totem"] = "Spell_Nature_TremorTotem",
    ["Mana Spring Totem"] = "Spell_Nature_ManaRegenTotem",
    ["Earthbind Totem"] = "Spell_Nature_EarthBindTotem",
    ["Searing Totem"] = "Spell_Fire_SearingTotem",
    ["Fire Resistance Totem"] = "Spell_FireResistanceTotem_01",
    ["Disease Cleansing Totem"] = "Spell_Nature_DiseaseCleansingTotem",
    ["Posion Cleansing Totem"] = "Spell_Nature_PoisonCleansingTotem",
    ["Grace of Air Totem"] = "Spell_Nature_InvisibilityTotem",
    ["Frost Resistance Totem"] = "Spell_FrostResistanceTotem_01",
    ["Grounding Totem"] = "Spell_Nature_GroundingTotem",
    ["Nature Resistance Totem"] = "Spell_Nature_NatureResistanceTotem",
    ["Stoneskin Totem"] = "Spell_Nature_StoneSkinTotem",
    ["Fire Nova Totem"] = "Spell_Fire_SealOfFire",
    ["Magma Totem"] = "Spell_Fire_SelfDestruct",
    ["Healing Stream Totem"] = "INV_Spear_04",
    -- Items --
    ["Molten Emberstone"] = "INV_Misc_Gem_Ruby_01",
    -- Heal --
    ["Ancestral Spirit"] = "Spell_Nature_Regenerate",
    ["Chain Heal"] = "Spell_Nature_HealingWaveGreater",
    ["Healing Wave"] = "Spell_Nature_MagicImmunity",
}
